const PH = 'https://placehold.co/800x1000/EDEAE4/928D84?text=Photo+Coming+Soon';

export const products = [
  {
    id:    0,
    name:  'The Rooster',
    cat:   'Birds',
    price: 2190,
    sold:  false,
    desc:  "A bold, colourful celebration of one of Africa's most recognised birds. The Rooster stands tall with an air of confidence — its comb and tail feathers rendered in vibrant reds, oranges, and golden yellows. A piece that commands attention from across a room.",
    size:  'To be confirmed',
    mats:  'Glass seed beads, wire armature',
    beads: 'To be confirmed',
    time:  'Approx. 2–3 weeks',
    imgs:  ['https://oldnickvillage.co.za/wp-content/uploads/2025/06/50.jpg', PH, PH, PH],
  },
  {
    id:    1,
    name:  'The Elephant',
    cat:   'Wild',
    price: 2400,
    sold:  false,
    desc:  "Africa's most beloved animal, reimagined in thousands of hand-placed glass beads. The Elephant stands with quiet dignity — a symbol of wisdom, strength, and memory. Rich earth tones and warm ambers give the surface a warmth that shifts beautifully in different lights.",
    size:  'To be confirmed',
    mats:  'Glass seed beads, wire armature',
    beads: 'To be confirmed',
    time:  'Approx. 4–5 weeks',
    imgs:  [PH, PH, PH, PH],
  },
  {
    id:    2,
    name:  'The Lion',
    cat:   'Wild',
    price: 2200,
    sold:  false,
    desc:  'Proud, powerful, and present. The Lion is rendered in warm golden and amber beads, with a dark mane that frames a face of quiet authority. One of the most technically challenging pieces in the collection.',
    size:  'To be confirmed',
    mats:  'Glass seed beads, wire armature',
    beads: 'To be confirmed',
    time:  'Approx. 3–4 weeks',
    imgs:  [PH, PH, PH, PH],
  },
  {
    id:    3,
    name:  'Beaded Protea',
    cat:   'Floral',
    price: 1200,
    sold:  false,
    desc:  "The Protea — South Africa's national flower — interpreted through colour and bead. Layers of pale pinks, creamy whites, and blush tones build outward from a dense, textured centre.",
    size:  'To be confirmed',
    mats:  'Glass seed beads, wire stem',
    beads: 'To be confirmed',
    time:  'Approx. 1.5–2 weeks',
    imgs:  ['https://oldnickvillage.co.za/wp-content/uploads/2025/06/51.jpg', PH, PH, PH],
  },
  {
    id:    4,
    name:  'Wire Fairie',
    cat:   'Wire',
    price: 980,
    sold:  false,
    desc:  "Elegant and elongated, the Wire Fairie showcases Tinashe's mastery of form through wire alone. The piece balances delicacy and structural precision — a fairie.",
    size:  'To be confirmed',
    mats:  'Decorative wire, beaded accents',
    beads: 'Accent beads',
    time:  'Approx. 1–2 weeks',
    imgs:  ['https://oldnickvillage.co.za/wp-content/uploads/2025/06/48.jpg', PH, PH, PH],
  },
  {
    id:    5,
    name:  'The Peacock',
    cat:   'Birds',
    price: 2600,
    sold:  false,
    desc:  "The most elaborate bird in the collection. The Peacock's tail is a breathtaking spread of iridescent teals, deep blues, and electric greens — thousands of beads forming the signature eye pattern.",
    size:  'To be confirmed',
    mats:  'Glass seed beads, wire armature, iridescent beads',
    beads: 'To be confirmed',
    time:  'Approx. 5–6 weeks',
    imgs:  [PH, PH, PH, PH],
  },
  {
    id:    6,
    name:  'The Zebra',
    cat:   'Wild',
    price: 1950,
    sold:  false,
    desc:  "Bold, graphic, and unmistakably African. The Zebra's black and white stripe pattern is rendered with extraordinary precision — each stripe individually beaded, creating a surface with subtle three-dimensionality.",
    size:  'To be confirmed',
    mats:  'Glass seed beads, wire armature',
    beads: 'To be confirmed',
    time:  'Approx. 3 weeks',
    imgs:  [PH, PH, PH, PH],
  },
  {
    id:    7,
    name:  'The Flamingo',
    cat:   'Birds',
    price: 1750,
    sold:  false,
    desc:  'Graceful and otherworldly, the Flamingo stands on one leg in its characteristic pose — a pastel study in balance. Soft pinks deepen to rose and coral at the wing tips and beak.',
    size:  'To be confirmed',
    mats:  'Glass seed beads, wire armature',
    beads: 'To be confirmed',
    time:  'Approx. 2.5 weeks',
    imgs:  [PH, PH, PH, PH],
  },
  {
    id:    8,
    name:  'The Rhino',
    cat:   'Wild',
    price: 2800,
    sold:  false,
    desc:  "Powerful and textured, the Rhino carries a commanding presence. Its hide is suggested through layers of grey, stone, and warm brown beads. A piece that honours one of Africa's most threatened animals.",
    size:  'To be confirmed',
    mats:  'Glass seed beads, wire armature',
    beads: 'To be confirmed',
    time:  'Approx. 5 weeks',
    imgs:  [PH, PH, PH, PH],
  },
];
