// data.js — Product catalog with Shopify variant IDs

export const products = [
  {
    id: 101,
    name: "Barrel Swing",
    artist: "Paivepo Studio",
    cat: "Furniture",
    price: null,
    sold: false,
    desc: "A handcrafted Barrel Swing currently listed in the Paivepo WhatsApp catalogue.",
    size: null,
    mats: null,
    beads: null,
    time: null,
    image: null,
    imageWebp: null,
    alt: "Barrel Swing by Paivepo Studio",
    whatsappLink: ""
  },
  {
    id: 102,
    name: "Leo",
    artist: "William Mwale",
    cat: "Paintings",
    price: null,
    sold: false,
    desc: "Leo — a leopard artwork currently listed in the Paivepo WhatsApp catalogue.",
    size: null,
    mats: "Acrylic on canvas",
    beads: null,
    time: null,
    image: null,
    imageWebp: null,
    alt: "Leo leopard painting by William Mwale",
    whatsappLink: ""
  },
  {
    id: 103,
    name: "Beauty in Colour, by William Mwale",
    artist: "William Mwale",
    cat: "Paintings",
    price: null,
    sold: false,
    desc: "Beauty in Colour, by William Mwale. Listed in the current Paivepo WhatsApp catalogue.",
    size: "1.5m × 1m",
    mats: "Acrylic on canvas",
    beads: null,
    time: null,
    image: null,
    imageWebp: null,
    alt: "Beauty in Colour acrylic painting by William Mwale",
    whatsappLink: ""
  },
  {
    id: 104,
    name: "Thinking Man",
    artist: "Paivepo",
    cat: "Sculpture",
    price: null,
    sold: false,
    desc: "Thinking Man — a sculptural work currently listed in the Paivepo WhatsApp catalogue.",
    size: null,
    mats: null,
    beads: null,
    time: null,
    image: null,
    imageWebp: null,
    alt: "Thinking Man sculpture from Paivepo",
    whatsappLink: ""
  },
  {
    id: 105,
    name: "Changamire the Rooster",
    artist: "Tinashe Kachama",
    cat: "Sculpture",
    price: null,
    sold: false,
    desc: "Changamire the Rooster — a handcrafted artwork currently listed in the Paivepo WhatsApp catalogue.",
    size: null,
    mats: null,
    beads: null,
    time: null,
    image: null,
    imageWebp: null,
    alt: "Changamire the Rooster sculpture by Tinashe Kachama",
    whatsappLink: ""
  },
  {
    id: 106,
    name: "Midnight Ruby",
    artist: "Tinashe Kachama",
    cat: "Sculpture",
    price: null,
    sold: false,
    desc: "Midnight Ruby — a handcrafted artwork currently listed in the Paivepo WhatsApp catalogue.",
    size: null,
    mats: null,
    beads: null,
    time: null,
    image: null,
    imageWebp: null,
    alt: "Midnight Ruby sculpture by Tinashe Kachama",
    whatsappLink: ""
  },
  {
    id: 107,
    name: "Earrings — Black",
    artist: "Paivepo",
    cat: "Jewellery",
    price: null,
    sold: false,
    desc: "Black earrings currently listed in the Paivepo WhatsApp catalogue.",
    size: null,
    mats: null,
    beads: null,
    time: null,
    image: null,
    imageWebp: null,
    alt: "Black handcrafted earrings from Paivepo",
    whatsappLink: ""
  },
  {
    id: 108,
    name: "Earrings — Multicolour",
    artist: "Paivepo",
    cat: "Jewellery",
    price: null,
    sold: false,
    desc: "Multicolour earrings currently listed in the Paivepo WhatsApp catalogue.",
    size: null,
    mats: null,
    beads: null,
    time: null,
    image: null,
    imageWebp: null,
    alt: "Multicolour handcrafted earrings from Paivepo",
    whatsappLink: ""
  },
  {
    id: 109,
    name: "Protea (White)",
    artist: "Tinashe Kachama",
    cat: "Floral",
    price: null,
    sold: false,
    desc: "Protea (White) — a handcrafted beaded floral artwork currently listed in the Paivepo WhatsApp catalogue.",
    size: null,
    mats: null,
    beads: null,
    time: null,
    image: null,
    imageWebp: null,
    alt: "White Protea beaded artwork by Tinashe Kachama",
    whatsappLink: ""
  },
  {
    id: 110,
    name: "Keyring",
    artist: "Paivepo",
    cat: "Accessories",
    price: null,
    sold: false,
    desc: "A handcrafted keyring currently listed in the Paivepo WhatsApp catalogue.",
    size: null,
    mats: null,
    beads: null,
    time: null,
    image: null,
    imageWebp: null,
    alt: "Handcrafted beaded keyring from Paivepo",
    whatsappLink: ""
  }
];

// FEATURED PIECE IDs (shown on homepage)
export const FEATURED_IDS = [101, 102, 103];

// ARTISTS
export const artists = [
  {
    id: "william",
    name: "William Mwale",
    origin: "Malawi → South Africa",
    role: "Painter",
    bio: "Telling stories through colour and canvas. Wildlife. Portraits. The African landscape alive in every brushstroke.",
    image: "images/artist-william.webp",
    imageWebp: "images/artist-william.webp",
    filter: "Paintings"
  },
  {
    id: "allick",
    name: "Allick",
    origin: "Zimbabwe → South Africa",
    role: "Painter & Artist",
    bio: "Handcrafted African expression through paint and form. Each canvas is a conversation between culture and canvas.",
    image: "images/artist-allick.webp",
    imageWebp: "images/artist-allick.webp",
    filter: "Paintings"
  },
  {
    id: "tinashe",
    name: "Tinashe Kachama",
    origin: "Zimbabwe → South Africa",
    role: "Founder & Beadwork Sculptor",
    bio: "Founder of Paivepo. Beadwork sculptor rooted in Shona heritage — bead by bead, story by story.",
    image: "images/artist-portrait.webp",
    imageWebp: "images/artist-portrait.webp",
    page: "about"
  }
];